load_model:
  INSTRUCTION_KEY: ">>TITLE<<"
  QUESTION_KEY: ">>QUESTION<<"
  ANSWER_KEY: ">>ANSWER<<"
  SUMMARY_KEY: ">>SUMMARY<<"
  CONTEXT_KEY: ">>DOMAIN<<"
  EN_KEY: ">>EN<<"
  TR_KEY: ">>TR<<"
  NER_CONTEXT_KEY: ">>NER_CONTEXT<<"
  NER_CLASS_KEY: ">>NER_CLASS<<"
  NER_RESPONSE_KEY: ">>NER_RESPONSE<<"
  KEYS_AS_SPECIAL_TOKENS: True

load_data:
  INSTRUCTION_KEY: ">>TITLE<<"
  QUESTION_KEY: ">>QUESTION<<"
  ANSWER_KEY: ">>ANSWER<<"
  SUMMARY_KEY: ">>SUMMARY<<"
  CONTEXT_KEY: ">>DOMAIN<<"
  ABSTRACT_KEY: ">>ABSTRACT<<"
  EN_KEY: ">>EN<<"
  TR_KEY: ">>TR<<"
  NER_CONTEXT_KEY: ">>NER_CONTEXT<<"
  NER_CLASS_KEY: ">>NER_CLASS<<"
  NER_RESPONSE_KEY: ">>NER_RESPONSE<<"
  INTRO_TRANSLATION: Aşağıda bir görevi tanımlayan bir yönerge ve bu yönergenin bağlamını içeren bir paragraf var. Yönergenin tanımladığı görevi yerine getirecek bir cevap üret.
  INTRO_SUMMARY: Aşağıda bir görevi tanımlayan bir yönerge ve bu yönergenin bağlamını içeren bir paragraf var. Yönergenin tanımladığı görevi yerine getirecek bir cevap üret.
  INTRO_QA: İçerikten soruyu cevapla.
  INTRO_NER: Aşağıda bir görevi tanımlayan bir yönerge ve bu yönergenin bağlamını içeren bir paragraf var. Yönergenin tanımladığı görevi yerine getirecek bir cevap üret.
  ### Prompt engineerları göreve davet ediyoruz!!!
  CUTOFF_LEN: 512

get_lora_model:
  use_peft: True
  LORA_R: 64
  LORA_ALPHA: 16
  LORA_DROPOUT: 0.1
  INT8_TRAINING: False

train_model:
  MICRO_BATCH_SIZE: 2
  BATCH_SIZE: 2
  EPOCHS: 10
  LEARNING_RATE: 1.85e-4  #2e-5
  EVAL_PER_EPOCH: 5
